public/manifest.json, src/App.js, src/assets/styles/abstracts/_mixins.scss, src/assets/styles/components/ChatDate.scss, src/assets/styles/components/HeaderChat.scss, src/assets/styles/components/HeaderLandingPage.scss, src/assets/styles/components/HelpLandingPage.scss, src/assets/styles/components/ReactionChat.scss, src/assets/styles/components/RichInput.scss, src/assets/styles/components/ThreadLandingPage.scss, src/assets/styles/components/aside.scss, src/assets/styles/components/boxChatMessage.scss, src/assets/styles/components/modals/ModalEditUser.scss, src/assets/styles/pages/LandingPage.scss, src/components/Aside.js, src/components/BoxChatMessage.js, src/components/ChatDate.js, src/components/HeaderLandingPage.js, src/components/HelpLandingPage.js, src/components/RichInput.js, src/components/ThreadChatMessage.js, src/components/ThreadLandingPage.js, src/components/ThreadMessage.js, src/components/modals/ModalEditUser.js, src/index.scss, src/pages/LandingPage.js, src/pages/Login.js
- [ //] 👌 Terminado y listo
- [// ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
=> add all components-frontend

src/assets/styles/components/ReactionChat.scss, src/assets/styles/components/aside.scss
- [x ] 👌 Terminado y listo
- [x ] 🐞 Bugfix (non-breaking changes que resuelve un problema
=> fix landingpage-bug

src/assets/styles/abstracts/_variables.scss, src/assets/styles/components/HeaderLandingPage.scss, src/assets/styles/components/ReplyMessagesChat.scss, src/assets/styles/components/ThreadLandingPage.scss, src/assets/styles/pages/LandingPage.scss, src/components/BoxChatMessage.js, src/components/HeaderLandingPage.js, src/components/HelpLandingPage.js, src/components/ReplyMessagesChat.js, src/components/RichInput.js, src/components/ThreadLandingPage.js, src/index.scss, src/pages/LandingPage.js
- [X ] 🤙 Solucion rapida
- [ X] 👌 Terminado y listo
- [X ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [X ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
=> Add reactions

src/assets/styles/components/ChannelMessageGroup.scss, src/assets/styles/components/DirectMessageUser.scss, src/assets/styles/components/aside.scss, src/components/Aside.js, src/components/ChannelMessageGroup.js, src/components/DirectMessageUser.js, src/index.scss
Se agrega en componente de canales y componente de mensajes directos y se muestran mediante un objeto:
tambien se agregan sus estilos, se modifica componente aside.js, aside.scss e index.scss
- [ x] 👌 Terminado y listo
- [ x] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
=> add component channel y direct message

src/assets/styles/components/HeaderChatGroup.scss, src/assets/styles/pages/LandingPage.scss, src/components/Aside.js, src/components/ChannelMessageGroup.js, src/components/DirectMessageUser.js, src/components/HeaderChatGroup.js, src/components/ThreadLandingPage.js, src/pages/LandingPage.js
- [X ] 👌 Terminado y listo
- [X ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
=> Add group-chat

package-lock.json, package.json, src/assets/mocks/list-member.json, src/components/ListMemberModals.js, src/components/modals/ModalMembersChannel.js
Se agregaron los mocks de los miembros de usuarios de un canal
se agrego axios.
- [ x] 👌 Terminado y listo
- [ x] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
=> add mocks members channel

package-lock.json, package.json, src/assets/mocks/channel.json, src/assets/mocks/chat.json, src/assets/mocks/users.json, src/assets/styles/components/HeaderChatGroup.scss, src/assets/styles/components/ReactionChat.scss, src/assets/styles/components/boxChatMessage.scss, src/assets/styles/pages/LandingPage.scss, src/components/Aside.js, src/components/BoxChatMessage.js, src/components/ChannelMessageGroup.js, src/components/DirectMessageUser.js, src/components/HeaderChatGroup.js, src/components/HeaderLandingPage.js, src/components/HelpLandingPage.js, src/components/ReplyMessagesChat.js, src/components/ThreadLandingPage.js, src/index.js, src/pages/LandingPage.js, src/store/actions.js, src/store/index.js
- [X ] 👌 Terminado y listo
- [ X] 🐞 Bugfix (non-breaking changes que resuelve un problema
=> Add feature-sprint-3

src/components/ReactionChat.js, src/pages/NotFound.js
Se agrego la funcionalidad de abrir y cerrar el hilo desde el icono de hilo de conversacion
- [ x] 👌 Terminado y listo
- [x ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
=> add reaction thread button

src/assets/styles/components/ReactionChat.scss, src/assets/styles/components/UserOptionsProfile.scss, src/components/ProfileLandingPage.js, src/components/ReactionChat.js, src/components/UserOptionsProfile.js
=> feat: update reactions

package-lock.json, package.json, src/assets/styles/components/HeaderLandingPage.scss, src/assets/styles/components/ProfileLandingPage.scss, src/assets/styles/components/UserOptionsProfile.scss, src/components/HeaderLandingPage.js, src/components/ProfileLandingPage.js, src/components/ReactionChat.js, src/components/UserOptionsProfile.js, src/pages/LandingPage.js, src/store/index.js
=> Feature redux

package-lock.json, src/components/ReactionChat.js
Se quito el boton duplicado de thread en el componente reaccion 
=> feat: delete button duplicate

package-lock.json, package.json, src/components/HeaderLandingPage.js, src/components/HelpLandingPage.js, src/components/ProfileLandingPage.js, src/components/ReactionChat.js, src/components/ReplyMessagesChat.js, src/components/ThreadLandingPage.js, src/components/UserOptionsProfile.js, src/index.js, src/pages/LandingPage.js, src/store/actions.js, src/store/actions/actionsChangeView.js, src/store/index.js, src/store/reducers/changeView.reducer.js, src/store/reducers/index.js
=> feat: organize store

package-lock.json, package.json, src/assets/styles/components/HelpLandingPage.scss, src/assets/styles/components/ThreadLandingPage.scss, src/components/HelpLandingPage.js
=> bugfix helpview

package-lock.json, src/assets/styles/components/PopoverComponent.scss, src/assets/styles/components/UserOptionsProfile.scss, src/components/HeaderLandingPage.js, src/components/PopoverComponent.js, src/components/UserOptionsProfile.js, src/pages/LandingPage.js, src/store/actions/actionsChangeState.js, src/store/reducers/changeState.reducer.js, src/store/reducers/index.js
=> bugfix option-profile

src/assets/styles/components/AddChannelOptions.scss, src/components/Aside.js, src/components/PopoverAddChannel.js, src/pages/LandingPage.js
=> fix: channel dropdown

src/App.js, src/assets/styles/components/AddChannelOptions.scss, src/assets/styles/components/aside.scss, src/components/AddChannelOptions.js, src/components/Aside.js, src/components/PopoverAddChannel.js, src/pages/Login.js, src/pages/Register.js, src/router/AuthRouter.js, src/router/PrivateRoute.js, src/router/PublicRoute.js, src/store/actions/actionsAuth.js, src/store/actions/actionsChangeState.js, src/store/reducers/auth.reducer.js, src/store/reducers/changeState.reducer.js, src/store/reducers/index.js
=> add private routes

package-lock.json, package.json, src/App.js, src/router/PrivateRoute.js, src/router/PublicRoute.js, src/store/actions/actionsAuth.js, src/store/reducers/auth.reducer.js
=> feat: navigate router

src/components/AddChannelOptions.js, src/components/PopoverAddChannel.js, src/components/PopoverComponent.js, src/components/UserOptionsProfile.js, src/components/modals/ModalCreateChannel.js, src/pages/LandingPage.js, src/store/actions/actionsChannel.js, src/store/reducers/channel.reducer.js
Crea un nuevo canal y solución de bugs.
=> feat: channel post and put

src/App.js, src/assets/styles/components/ListChannels.scss, src/components/AddChannelOptions.js, src/components/Aside.js, src/components/ChannelMessageGroup.js, src/components/ListChannels.js, src/components/ListMemberModals.js, src/components/PopoverAddChannel.js, src/components/modals/ModalCreateChannel.js, src/components/modals/ModalListChannels.js, src/pages/LandingPage.js, src/pages/Register.js, src/router/PrivateRoute.js, src/store/actions/actionsAuth.js, src/store/actions/actionsChannel.js, src/store/reducers/channel.reducer.js, src/store/reducers/index.js
[//]: <> Se agregaron las funcionalidades de crear canal y unirse a un canal con Redux. El sistema se actualiza en tiempo real
[//]: <>
=> add channels-post-put

src/components/UserOptionsProfile.js, src/pages/LandingPage.js, src/store/actions/actionsAuth.js, src/store/actions/actionsChannel.js, src/store/reducers/auth.reducer.js
=> add logout user

src/assets/styles/components/ListUsers.scss, src/components/Aside.js, src/components/ListUsers.js, src/components/modals/ModalListUsers.js, src/pages/LandingPage.js, src/store/actions/actionUsers.js, src/store/reducers/index.js, src/store/reducers/user.reducer.js
=> add list channels and list users

package-lock.json, package.json, src/App.js, src/assets/styles/pages/LoadingPage.scss, src/components/ListMemberModals.js, src/components/UserOptionsProfile.js, src/components/modals/ModalEditUser.js, src/components/modals/ModalMembersChannel.js, src/index.scss, src/pages/LandingPage.js, src/pages/LoadingPage.js, src/pages/Login.js, src/router/AuthRouter.js, src/store/actions/actionUsers.js, src/store/actions/actionsAuth.js, src/store/reducers/auth.reducer.js, src/store/reducers/user.reducer.js
- [ x] 🤙 Solucion rapida
- [ x] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
=> feat: add edit profile

package-lock.json, package.json, src/components/UserOptionsProfile.js, src/hooks/useSocket.js, src/index.js, src/pages/LandingPage.js, src/pages/Login.js, src/store/actions/actionsChat.js, src/store/actions/actionsSocket.js, src/store/reducers/chat.reducer.js, src/store/reducers/index.js, src/store/reducers/socket.reducer.js
- [x ] 👌 Terminado y listo
- [x ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
=> feature socket config client

src/components/Aside.js, src/components/DirectMessageUser.js, src/components/ImageProfileUser.js, src/components/modals/ModalEditUser.js, src/router/AuthRouter.js, src/store/reducers/auth.reducer.js
- [x ] 🤙 Solucion rapida
- [x ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
=> feature list users

src/components/Aside.js, src/components/UserOptionsProfile.js, src/hooks/useSocket.js, src/pages/LandingPage.js, src/store/actions/actionsSocket.js, src/store/reducers/index.js, src/store/reducers/socket.reducer.js
=> add get user with sockets

src/components/BoxChatMessage.js, src/components/DirectMessageUser.js, src/components/HeaderChat.js, src/components/RichInput.js, src/components/modals/ModalEditUser.js, src/components/modals/ModalListChannels.js, src/pages/LandingPage.js, src/store/actions/actionsSocket.js, src/store/reducers/socket.reducer.js
=> feature add scroll bottom

src/assets/styles/components/PopoverComponent.scss, src/assets/styles/components/UserOptionsProfile.scss, src/components/PopoverComponent.js, src/components/ProfileLandingPage.js, src/components/UserOptionsProfile.js
=> feat: show user profile

package-lock.json, package.json, src/components/BoxChatMessage.js, src/components/ChatDate.js, src/components/RichInput.js, src/helpers/timeDate.js, src/store/reducers/socket.reducer.js
=> chat config frontend

src/assets/styles/components/ListChannels.scss, src/components/HeaderChat.js, src/components/HeaderChatGroup.js, src/components/ListChannels.js, src/components/ListMemberModals.js, src/components/modals/ModalMembersChannel.js, src/pages/LandingPage.js
=> feature-add-user-to-channel

src/components/ListMemberModals.js, src/components/modals/ModalMembersChannel.js
=> bugfix add user to channel

src/components/HeaderChat.js
=> bugfix channels

src/components/ChannelMessageGroup.js, src/components/HeaderChat.js, src/components/RichInput.js, src/pages/LandingPage.js, src/store/actions/actionsSocket.js
=> group chat

src/App.js, src/assets/styles/components/UserOptionsProfile.scss, src/components/UserOptionsProfile.js, src/pages/ChangePassword.js, src/router/AuthRouter.js, src/router/NoAuthRouter.js, src/store/actions/actionUsers.js, src/store/reducers/user.reducer.js
=> feature change password

src/components/UserOptionsProfile.js
=> bugfix when thread is open and logout session

src/assets/styles/pages/LandingPage.scss, src/components/RichInput.js, src/components/RichInputThread.js, src/pages/LandingPage.js
=> add input characteristics

src/App.js, src/assets/styles/pages/LandingPage.scss, src/pages/LandingPage.js, src/pages/Login.js, src/pages/RecoverPassword.js, src/pages/ResetPassword.js, src/store/actions/actionUsers.js, src/store/reducers/user.reducer.js
=> feat: landing page welcome, restore page

src/assets/styles/components/HeaderLandingPage.scss, src/assets/styles/components/ProfileLandingPage.scss, src/assets/styles/components/UserOptionsProfile.scss, src/components/AddChannelOptions.js, src/components/Aside.js, src/components/FooterLoginRegister.js, src/components/HeaderChat.js, src/components/HeaderLandingPage.js, src/components/HeaderLoginRegister.js, src/components/ListChannels.js, src/components/ListMemberModals.js, src/components/ListUsers.js, src/components/ProfileLandingPage.js, src/components/UserOptionsProfile.js, src/components/modals/ModalCreateChannel.js, src/components/modals/ModalListUsers.js, src/pages/ChangePassword.js, src/pages/Login.js, src/pages/NotFound.js, src/pages/RecoverPassword.js, src/pages/Register.js, src/pages/ResetPassword.js, src/pages/Response.js
- [x ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
=> add english version

src/assets/styles/components/DirectMessageUser.scss, src/assets/styles/components/PopoverComponent.scss, src/assets/styles/components/UserOptionsProfile.scss, src/components/DirectMessageUser.js, src/components/HeaderLandingPage.js, src/components/PopoverComponent.js, src/components/UserOptionsProfile.js, src/pages/LandingPage.js, src/pages/Login.js, src/pages/NotFound.js, src/pages/Register.js
=> state away added, userOptionProfile modified, loginPage modified

src/assets/styles/components/DirectMessageUser.scss, src/assets/styles/components/PopoverComponent.scss, src/assets/styles/components/modals/ModalEditUser.scss, src/components/modals/ModalEditUser.js
=> bugfix edit user

src/assets/styles/components/ListUsers.scss, src/assets/styles/components/ProfileLandingPage.scss, src/components/Aside.js, src/components/ListMemberModals.js, src/components/ListUsers.js, src/components/ShowUsersProfile.js, src/components/modals/ModalBecomePremium.js, src/components/modals/ModalListUsers.js, src/pages/LandingPage.js, src/store/actions/actionUsers.js, src/store/reducers/user.reducer.js
=> add show profiles to users

src/assets/styles/components/addWorkspaceOption.scss, src/assets/styles/components/aside.scss, src/assets/styles/components/modals/ModalCreateChannel.scss, src/components/Aside.js, src/components/BoxChatMessage.js, src/components/PopoverAddChannel.js, src/components/addWorkspaceOption.js, src/components/modals/ModalCreateChannel.js, src/components/modals/ModalCreateWorkspace.js, src/pages/LandingPage.js, src/pages/Register.js, src/store/actions/actionsAuth.js, src/store/actions/actionsChannel.js, src/store/reducers/auth.reducer.js, src/store/reducers/socket.reducer.js
=> feature workspace

.gitignore, package-lock.json, package.json, src/components/HelpLandingPage.js, src/components/PopoverComponent.js, src/components/UserOptionsProfile.js, src/components/modals/ModalCreateWorkspace.js, src/components/modals/ModalEditUser.js, src/pages/LandingPage.js, src/pages/Login.js, src/pages/RecoverPassword.js, src/pages/Register.js, src/pages/ResetPassword.js, src/store/actions/actionsAuth.js
=> bug field form

src/components/AddChannelOptions.js, src/components/ListChannels.js, src/components/ListWorkspace.js, src/components/PopoverAddChannel.js, src/components/RichInput.js, src/components/RichInputThread.js, src/components/addWorkspaceOption.js, src/components/modals/ModalCreateChannel.js, src/components/modals/ModalCreateWorkspace.js, src/components/modals/ModalListChannels.js, src/components/modals/ModalListWorkspace.js, src/pages/Register.js
=> bugs: send messages
